apiVersion: apps/v1
kind: Deployment
metadata:
  name: client-flask
spec:
  replicas: 1
  selector:
    matchLabels:
      app: client-flask
  template:
    metadata:
      labels:
        app: client-flask
    spec:
      containers:
      - name: client-flask
        image: eu.gcr.io/distributed-dijkstra/client_test:latest
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        env:
          - name: MY_IP
            valueFrom:
              fieldRef:
                fieldPath: status.podIP
        ports:
        - containerPort: 80
        command: ['sh', '-c', 'python client_test.py ${MAIN_SERVICE_SERVICE_HOST}:5001 ${MY_IP}:5006 0.0.0.0 80']
---

apiVersion: v1
kind: Service
metadata:
  name: client-flask-service
spec:
  selector:
    app: client-flask
  ports:
  - port: 80
    targetPort: 80
  type: LoadBalancer
